services:
  website:
    build: ./frontend
    container_name: website
    ports:
      - "3000:3000"
    # Comente as 3 linhas de volumes abaixo para o Docker não tentar ler a rede em tempo real:
    # volumes:
    #   - ./frontend:/app
    #   - /app/.next
    #   - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    restart: unless-stopped